boost-ext/ut

example/exceptions.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- Abort is called on active exception and tests aren't failing.
Solution:
- Handle active exception and report a failure.
=> :new: [exceptions] Fail on active exception

CMakeLists.txt
this patch adds build options to disable building the tests, examples and benchmarks as well as adds an install target
=> add build options and install target

README.md, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
-
Solution:
-
Issue: #
Reviewers:
@
=> :new: :art: [ut] Nicely print `throws/nothrow/aborts` info on failure

example/CMakeLists.txt
Avoids cmake warning: "Argument not separated from preceding token by
whitespace."
Problem:
-
Solution:
-
Issue: #
Reviewers:
@
=> Remove unnecessary comma

include/boost/ut.hpp
Problem:
This method definition caused compiler issues: [[nodiscard]] constexpr auto min(const T& lhs, const T& rhs) -> const T&
This was due to a previous include having a macro definition for the min function
Solution:
undef min :)
=> Undefined min macros to prevent conflicts with min method declaration

README.md
Problem:
- There is no way to share questions about UT using a chat.
Solution:
- Add support for chatting about UT with Gitter.
=> :books: [README] Add a Gitter chat badge

example/section.cpp, include/boost/ut.hpp
Problem:
- `section` example doesn't show how to deal with move-only types.
Solution:
- Add 2 additional tests which show how move move-only types into tests (based on std::stringstream).
=> :art: :new: [example] Extend `section` example with move-only types

example/cfg/runner.cpp, example/exception.cpp
Problem:
- `runtime_error` with an empty `{}` is being thrown causing UB.
- There is missing `stdexcept` include.
Solution:
- Use a `"exception!"` string instead.
- Add missing include.
=> :bug: [example] Runner Example Segfaults, Fix #271

README.md
Problem:
- There are a few typos in README.
- The specification is missing `const` in some cases.
Solution:
- Fix them.
- Add `const` to follow the implementation.
=> :art: [README] Fix typos/specification

README.md, example/matcher.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- `matcher` operator is not required.
Solution:
- Remove it and update examples without using it.
=> :fire: :art: [ut] Remove `matcher` operator

example/matcher.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- `source_location` is using `__has_builtin` to detect whether `source_location` is available which is reliably.
Solution:
- Use `compiler` information instead.
=> :bug: [ut] Fix  issue with detecting availability of `source_location`

README.md
Problem:
- Godbolt link to the `matcher` example doesn't compile because matcher
was removed.
Solution:
- Fix the link by removing matcher from the example.
=> :books: [README] Fix broken `matcher` godbolt link

.travis.yml, README.md, example/CMakeLists.txt, example/cfg/parallel_runner.cpp, include/boost/ut.hpp
Problem:
- There is no example which shows how to run test suites in parallel.
Solution:
- Add `parallel_execution` example which leverages `std::execution::par` policy.
=> :new: [example] Parallel execution

README.md, include/boost/ut.hpp
Problem:
- There are new features which aren't tagged in `1.1.5` version.
Solution:
- Update version to `1.1.6`
=> :arrow_up: [version] Bump version to `1.1.6`

README.md
Problem:
- Supported compilers do not mention Clang-cl.
Solution:
- Update REAMDE with Clang-cl.
Problem:
-
Solution:
-
Issue: #
Reviewers:
@
=> :arrow_up: :books: [README] Overview with Clang-cl support

include/boost/ut.hpp
Problem:
- UT doesn't compile with GCC-10 due to using of `std::operators`.
Solution:
- Remove them for GCC >= 10.
Note:
- Using `std::operators` is still required for GCC < 10. It's not required for GCC >= 10, Clang, MSVC.
Problem:
-
Solution:
-
Issue: #
Reviewers:
@
=> :bug: [ut] Fails to compile with GCC-10, Fix #292

include/boost/ut.hpp
Problem:
- Apple defines `__has_builtin` to 0.
Solution:
- Undefine `__has_builtin` when Apple is detected.
=> :bug: [gcc-9/apple] Fix for `__has_builtin` defined to 0

include/boost/ut.hpp, test/ft/test_suite_3.cpp
Problem:
- When `BOOST_UT_FORWARD` is defined log functionality doesn't compile.
Solution:
- Add missing overloads for the `on` call with different types of `log`.
=> :bug: Logging does not work with `BOOST_UT_FORWARD`, Fix #297

include/boost/ut.hpp
`auto i = 0u` means that the type of `i` is `unsigned` which is 32-bit on MSVC. However, `std::size(input)` returns `std::size_t` which is 64-bit on MSVC x64. This means `++i` will result in integer overflow when it reaches 2^32.
Problem:
The type of `i` is 32-bit, but it is compared to 64-bit value which can result in the integer overflow.
Solution:
Make the type of `i` corresponding to `std::size(input)`
Reviewers:
@
=> Security fix

CMakeLists.txt
Problem:
- CMake Warning (dev) at cmake-build-debug/_deps/ut-src/CMakeLists.txt:41 (elseif):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Quoted variables like "MSVC" will no longer be dereferenced when the policy
is set to NEW.  Since the policy is not set the OLD behavior will be used.
Solution:
- Update the minimum CMake version to 3.1 to silent the warning (https://cmake.org/cmake/help/latest/policy/CMP0054.html)
=> :bug: :wrench: [cmake] Silence CMake Policy Warning CMP0054, Fix #305

README.md
Problem:
- README doesn't have godbolt link to `how-does-it-work`.
Solution:
- Add link to godbolt.
=> :books: [README] Godbolt link to `how-does-it-work`

example/expect.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- Use `true_b/false_` doesn't say much about the intent.
Solution:
- Named boolean expressions makes it convenient and cleaner.
=> :new: [ut] Add `""_b` named boolean expression

include/boost/ut.hpp
Problem:
- expect is not an operator but it should be to allow `!expect(ptr) and expect(ptr)`.
Solution:
- Inherit from `op` to allow `expect` to be treated as an operator.
- Unify naming and add the explicit conversion to bool.
=> :art: [ut] `expect` should be treated as an operator

README.md, example/spec.cpp
Problem:
- There are no `spec` examples in the `README`.
Solution:
- Extend `README` to show how to use `spec` syntax.
- Fix godbolt links.
=> :books: [README] `Spec` examples

README.md, example/terse.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- Not all operators have been supported with `terse` syntax.
Solution:
- Add support for `terse` syntax with `==, !=, >, >=, <, <=` operators.
=> :art: :new: [terse] Support all operators with `terse` syntax

README.md
Problem:
- There are no `terse` notation examples in README.
- Godbolt link to `try-it-online` is broken.
Solution:
- Add `terse` notation examples to the tutorial.
- Fix the link. Use the same as for the `quick-start`.
=> :books: [README] Add `terse` notation examples to tutorial

conanfile.py
Problem:
- Boost.UT is not available in any remote package management system
Solution:
- Add initial `conanfile.py`
Issue: #
Reviewers:
@
=> :package: [package] conan.io recipe

example/terse.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- There is no easy way to compare custom types with terse notation.
Solution:
- Add `%_t` notation to simplify the comparison.
- Extend `terse` example.
Example:
```
foo{43, true}%_t == foo{42, true}; // FAILED:__LINE__: foo{43, true} == foo{42, true}
```
=> :new: [terse] Support for comparing objects with `%_t` notation

include/boost/ut.hpp
Problem:
- GCC complaints about locally unused type.
Solution:
- Apply `[[maybe_unused]]`` to locally defined types.
=> :art: [ut] Apply `[[maybe_unused]]` for locally defined types

example/terse.cpp, test/ut/ut.cpp
Problem:
- clang-format changes `%_t` into ` % _t`.
Solution:
- Disable clang-format around usage of `%_t`.
=> :lipstick: [terse] Disable clang-format for `%_t` notation

example/terse.cpp
Problem:
- `terse` example doesn't show how to use functions to compare types.
Solution:
- Extend `terse` example to demonstrate the functionality.
=> :art: [terse] Improve `terse` example

example/BDD.cpp
Problem:
- `terse` operators are [[nodiscard]] and they result is based on the operation side offect.
Solution:
- Use `operators::terse` in BDD example.
=> :bug: [example] `BDD` example should use terse operators

include/boost/ut.hpp
Problem:
- GCC-10 gets into an infinite recursion with string_views.
Solution:
- Use `using std::operator` to prioritize builtin operators and break the infinite recursion.
=> :bug: [operators] GCC-10 Infinite Recursion in operator==, Fix #330

example/terse.cpp, include/boost/ut.hpp
Problem:
- `""_b` operator is not exposed via literals namespace which is inconsistent.
Solution:
- Move it to literals namespace.
=> :new: :art: [literals] Move `""_b` to `literals` namespace

README.md, example/CMakeLists.txt, example/benchmark.cpp
Problem:
- UT doesn't support micro-benchmarking out of the box.
- There is no info about micro-benchmarking in `README`.
Solution:
- Add example how to add/integrate micro-benchamarking with UT.
- Add C++ micro-benchmarking libraries to `README` `FAQ`.
=> :new: [example] `micro-benchmarking`, Fix #276

README.md
Problem:
- Benchmark link is broken in Fast compilation times section.
Solution:
- Fix it by using `a href` instead of Markdown.
=> :books: [README] FAQ - fix benchmark link

CMakeLists.txt
It's impossible to disable building benchmarks, examples and tests in top-level builds. When packaging this is quite undesirable, as this results in having to build tons of irrelevant targets.
Make the relevant flags cache variables so they can be overridden for such builds.  
Uses the same logic as before for setting the default values.
=> Allow disabling benchmarks, examples and tests in top-level builds

CMakeLists.txt, cmake/ut-config.cmake.in
Allows packaging μt in distributions and easily using it in other programs using `find_package()`.
E.g.
```
find_package(ut)
target_link_libraries(my_thing PRIVATE boost::ut)
```
`boost.ut` target was named to `ut` to result in the correct imported target name (`boost::ut`).
Testing target `ut` was renamed to `ut.test` to avoid a naming conflict.
=> CMake config

.travis.yml
Problem:
- `osx` image is out of date and flaky.
Solution:
- Update it to xcode11.3.
=> :arrow_up: [travis/osx] Update image to `xcode11.4`

example/BDD.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- Only `given/when/then` steps are supported for BDD workflow but naming is important.
Solution:
- Add `feature/scenario` to BDD support which mimics `gherkin` support.
=> :new: [BDD] Support for `features/scenario`

README.md
Problem:
- There is no info in README about benchmark example.
Solution:
- Add benchmark example to FAQ section
=> :books: [README] Info about benchmark example in FAQ

README.md, conanfile.py, include/boost/ut.hpp
Problem:
- `[Boost].UT` might be misleading.
Solution:
- Use `Boost::ext.UT` to indicate that it's an extension library and not part of Boost.
=> :art: :arrow_up: [UT] Use `[Boost::ext].UT` instead of `[Boost].UT`

example/CMakeLists.txt, include/boost/ut.hpp
Problem:
- Not all features are available in C++17 standard causing warning with GCC/Clang.
Solution:
- Enable tests in C++17 with GCC.
- Use C++17 features instead of C++20 when GCC/Clang report warnings.
=> :wrench: [UT] Fix warnings with C++17 standard

meson.build
Problem:
To work with C++ libraries in meson, the `meson.build` file is required.
If possible, please allow me to add.
We have confirmed that this configuration works properly in our local environment.
- [Subprojects - The Meson Build System](https://mesonbuild.com/Subprojects.html)
Solution:
- add `meson.build` in project root directory
=> Add meson support

include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- `den_size` for floating point has to respect possible number space.
Solution:
- Use `unsigned long` `unsigned long long` for den_size with `""_d` and `""_ld`.
=> :bug: [UT] `floating-point` den size can overflow

README.md, example/expect.cpp, example/fatal.cpp, example/macro.cpp, example/mut.cpp, example/parameterized.cpp, example/section.cpp, example/should.cpp, example/skip.cpp, example/tag.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- fatal assertions are only allowed with `expect` via `!expect` but not for expressions.
- `expect` is considered an operator but it's not really.
- `tags` are using `>>` operator which now colides with `>> fatal`.
Solution:
- Introduce `>> fatal` for expressions.
- Remove operator requirements from `expect`.
- Remove `!expect` syntax.
- Change `tags` to use `/` instead.
=> :new: :boom: :art: [UT] Fatal assertions with expressions

README.md
Problem:
- `godbolt` links aren't reflecting the newest changes to `fatal` assertions.
Solution:
- Fix them.
=> :books: [README] Update `godbolt` links

README.md, include/boost/ut.hpp
Problem:
- The current version is not reflecting stable/new features.
Solution:
- Update version to `1.1.8`.
=> :arrow_up: [ut] Bump version to `1.1.8`

example/fatal.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- There is no support of streaming messages to out with terse syntax.
Solution:
- Add support for `operator<<` with terse syntax.
=> :new: [Terse] Support for `operator<<`

README.md
Problem:
- C++17 support is advertised but it only works with Clang/GCC and not MSVC.
Solution:
- Remove mention of C++17 support as it's limited and not fully supported and/or maintained.
=> :books: [README] Remove C++17 support, Fix #378

README.md
Problem:
The value of `i` was set to 42, but the linked godbolt example runs the test with `int i = 43`. Therefore, either the code output below this snippet or the docs have to be updated. 
Solution:
This merge request replaces 42 with 43 to sync the output and the godbolt example.
=> Replace 42 with 43

README.md
Problem:
- Macro example link doesn't compile.
Solution:
- Fix the link.
=> :bug: :books: [README] Fix link to `macro` example

CMakeLists.txt
boost-ut is header-only so the CMake config should be installed into the architecture-independent directory to allow it to be found when compiling regardless of the targeted architecture and the architecture it was installed on.
=> CMake: Install config file into architecture-independent location

example/gherkin.cpp
Problem:
- `gherkin` example is quite hard to use with an external file.
Solution:
- Simplify it by adding a `file` expression to return the file content.
=> :art: [example] Simplify the `gherkin` usage with an external file

include/boost/ut.hpp
Problem:
- [Warning C4459](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4459?view=vs-2019) occurs when using this library in `MSVC-2020 CMake Project`.
Solution: 
- Rename the identifier in which the name conflict occurred.
=> [MSVC-2020] Fix MSVC warning C4459

example/fatal.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- There is a valid warning of potential misuse of comma operator in match function.
Solution:
- Use semicolon instead of a comma to avoid the warning and make the intend cleaner.
- Add gherkin unit test to verify the behaviour of match in an integration test.
=> :bug: [core] Warning: "Possible misuse of comma operator", Fix #398

example/benchmark.cpp, example/expect.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- When comparing `""_b` operators names aren't printed. Instead true/false are used.
- utility::string_view is not needed.
Solution:
- Introduce a local `named` operator which prints the underlying name.
- Remove utitlity::string_view.
=> :bug: [core] `""_b` should print names on failures

example/cfg/parallel_runner.cpp
Problem:
- When `ut::cfg` is overridden and included by multiple files it has to be marked inline.
Solution:
- Add inline to `ut::cfg` in examples.
=> :wrench: Mark `ut::cfg` inline when overriden, Fix #402

include/boost/ut.hpp
Problem:
- GCC warns about a missing initializer
Solution:
- add the missing initializer
=> fix GCC warning -Wmissing-field-initializers

README.md
Problem:
- There is no badge for conan center package.
- Github support discussions now.
Solution:
- Add conan center package badge to readme.
- Use Github discussions instead of gitter.
=> :arrow_up: :books: [README] UT conan-center badge

CMakeLists.txt
Problem:
- Projects importing boost.ut as a subproject will see "Policy CMP0077
is not set..." warning if they set any of the CMake options and are
using CMake version >= 3.13.
Solution:
- Specify a maximum version of 3.19 to cmake_minimum_required. This can
max can be periodically increased as new versions of CMake are
released.
=> Specifcy maximum CMake version

test/ut/ut.cpp
Problem
- gcc10 complains about float-equal comparison of floating point.
Solution:
- Fix the test by using _d UDL when comparing big floating point values.
=> :white_check_mark: :bug: [ut] Fix float-equal double comparison

include/boost/ut.hpp
Problem:
- `ut.hpp` doesn't compile when `__cpp_modules` is defined
Solution:
- Correctly close namespaces conditionally (as noted from https://github.com/microsoft/vscode-cpptools/issues/7150#issuecomment-796966568)
Issue: #432
Reviewers:
@michaelvlach can you please verify that this works on your end?
=> Fix compilation error with __cpp_modules

meson.build
Problem:
- When using ut as a Meson subproject, users have to do `dependency('boost.ut', fallback: ['ut', 'boostut_dep'])`.
Solution:
- Using Meson's 0.54 `override_dependency()`, users can now type `dependency('boost.ut', fallback: 'ut')`, saving a few characters and avoiding having to type the exact dependency variable name.
This does not affect users currently using the old method.
=> Improve Meson support - use `override_dependency()` in meson.build

CMakeLists.txt, include/boost/ut.hpp
Problem:
- Some compilers enable __cpp_module even if the header file is not used as module. This results in a compilation error with newer compilers like MSVC 19.29 (VS 16.10).
Solution:
- Add a macro to disable module in c++20.
Issue: Fixes #441
Reviewers:
@
=> Add option to disable module with c++20.

include/boost/ut.hpp
Problem:
- the following error is reported because clang-tidy doesn't include inline namespaces in the qualified name:
```
test/ut/ut.cpp:286:21: error: static_assert expression is not an integral constant expression [clang-diagnostic-error]
static_assert("void"sv ==
^
/Users/runner/work/ut/ut/build/../include/boost/ut.hpp:234:12: note: cannot refer to element 70 of array of 63 elements in a constant expression
return {&__PRETTY_FUNCTION__[70], sizeof(__PRETTY_FUNCTION__) - 72};
```
- clang-tidy reports the following warnings:
```
include/boost/ut.hpp:263:3: warning: multiple declarations in a single statement reduces readability [readability-isolate-declaration]
include/boost/ut.hpp:285:19: warning: do not declare C-style arrays, use std::array<> instead [modernize-avoid-c-arrays]
``` …
=> Reduce clang-tidy errors and warnings

.gitignore, include/boost/ut.hpp
Use std source_location if present
Problem:
-
Newest MSVC support source_location, but not used in this library
Solution:
-
Check __cpp_lib_source_location macro to add it
Issue: #
Reviewers:
@
=> fix(source location): improve msvc compatibility

example/CMakeLists.txt, example/attr.cpp
Problem:
- There is no example how assert/attributes can be used for explicit syntax.
Solution:
- Add example/attr to show the use case.
=> :new: [example] Attr/define

example/attr.cpp
Problem:
- Broken macOS CI build due to the following error:
```
../example/attr.cpp:20:16: error: expression result unused [-Werror,-Wunused-value]
expect(6_i == sum(1, 2, 3));
~~~~^~~~~~~~~~~~~~~
1 error generated.
```
Solution:
- Define expect macro using the comma operator to force the use of the expression value.
- Tested solution on macOS local build.
Issue: #
Reviewers:
=> Use built-in comma operator to evaluate expression

example/tmp.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- There is no easy way to compare type of function result.
Solution:
- Add support for `type<int> == f()` comparison.
=> :new: [core] Support for easy comparison of function result type

include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- Only int types are supported by the gherkin steps.
Solution:
- Introduce lexical cast in order to support multi-type expressions.
=> :bug: Add support for gherkin multi-type expressions, Fix #460

include/boost/ut.hpp
Problem:
Compilation generates warnings, specifically: name shadowing on GCC-9:
```
ut.hpp:1201:49: warning: declaration of ‘filter’ shadows a member of ‘boost::ext::ut::v1_1_8::runner<boost::ext::ut::v1_1_8::reporter<boost::ext::ut::v1_1_8::printer> >::filter’ [-Wshadow]
1201 |         : path_{utility::split(filter, delim)} {}
|                                                 ^
```
and missing variable declarations on clang-9, e.g.:
``` 
ut.hpp:378:16: warning: no previous extern declaration for non-static variable 'has_npos_v<boost::ext::ut::v1_1_8::detail::eq_<unsigned long, unsigned long> &>' [-Wmissing-variable-declarations]
constexpr auto has_npos_v = is_valid<T>([](auto t) -> decltype(void(t.npos)) {
```
Solution:
Name shadowing warnings are suppressed by refactoring the affected …
=> Fixing name shadowing warnings

include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- when a string parameter is parsed in a gherkin test clause, ut is ignoring
everything after the first whitespace character
Solution:
- introduce a special case for std::string in the lexical_cast
method of gherkin test not to rely on the streaming input operator
(works only until the first whitespace) but to take the whole value.
=> :bug: fix gherkin lexical_cast for string input parameters

include/boost/ut.hpp
Renamed `ios646.h` include check to `iso646.h`
Problem:
- There's a typo on checking if `iso646.h` can be included
Solution:
- Rename typo-ed `ios646.h` to `iso646.h`
=> Fix small typo on include

.github/workflows/macos.yml, include/boost/ut.hpp
Problem:
-
Compiler: Apple Clang 13
1.
```
error: array index 70 is past the end of the array (which contains 62 elements) [-Werror,-Warray-bounds]
return {&__PRETTY_FUNCTION__[70], sizeof(__PRETTY_FUNCTION__) - 72};
```
2.
`llvm/share/clang/run-clang-tidy.py` -> `llvm/bin/run-clang-tidy`
Solution:
-
1. Apply the same rule that is used for Clang 12.
2. Update new path for run-clang-tidy
=> Fix Apple Clang 13 compilation error

README.md
Problem:
The setup guide for CMake integration was misleading, the provided target name for `target_link_libraries` was not correct and wouldn't work.
Solution:
Fixing the typo.
Issue: #
Reviewers:
@
=> Updated README.md to refer to the correct target name

.github/workflows/windows.yml
Problem:
- Windows CI failing on master branch.
- GH Actions windows-latest defaults to 2022 image which includes VS 2022 instead of VS 2019.
Solution:
- Update the Windows CI to use VS 2022 generator now.
Issue: #
Reviewers:
=> Update Windows CI CMake Visual Studio generator

README.md
Problem:
- there exists a way to print the name of a type in templated tests, but it was not documented
Solution:
- added a small section beneath the _parameterized_ example
I tried to mimic the existing first-person style of writing. If that is not desired, I can revert the last commit.
Issue: #500
Reviewers:
=> Add documentation for `reflection::type_name<T>()`

include/boost/ut.hpp
Problem:
Currently, for container data types, the output is overloaded in the form `{element, ...}`. A container datatype is recognized if it has `begin()` and `end()` function members. The overloading excludes data types that have a public member `npos`. This probably refers to `string` and `string_view`.
This will override any user data type output that may have been defined! (E.g. multidimensional arrays.)
Solution:
- Replace string-like detection with output operator detection
- (Note: I also replaced `std::stringstream` by `std::ostringstream`.)
Issue: #493
Reviewers:
=> exclude any printable type from the container print overload

include/boost/ut.hpp, test/ut/ut.cpp
This allows users to check for approximate equality with a custom epsilon without touching `boost::ut::detail::value`.
Problem:
- Overriding the epsilon value for approximate equality/inequality requires explicit instantiation of `boost::ut::detail::value`. For an example, see: #451.
Solution:
- Provide a `near()` operation wrapper (similar to `eq()`) that takes an additional epsilon argument.
Issue: #451
Reviewers:
None (yet!)
=> Add a "near" operator

include/boost/ut.hpp, test/ut/CMakeLists.txt, test/ut/ut.cpp, test/ut/win_compat_test.cpp
Problem:
- clang-tidy failed to evaluate `declval<std::ostringstream>() << t`
- `std::numbers::pi_v` is a C++20 feature.
- `near` conflicts with Macro `near` defined in `<Windows.h>`
Solution:
- Use `declval<std::ostringstream&>() << t` instead.
- Remove use of `std::numbers::pi_v` since minimum support standard is C++17.
- Change `near` to `approx`.
Additional:
- Add `win_compat_test.cpp` to ensure no conflict with `<Windows.h>`
- Apply clang-format.
Issue: #509 #511 
Reviewers:
=> Fix all compilation errors at once.

.github/workflows/windows.yml, example/expect.cpp, example/parameterized.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- `ut` can only be compiled by MSVC w/ clang-cl on Windows.
Solution:
- Make `ut` to be compiled by MSVC w/ v143 toolset as well.
- Update Windows CI to build code with MSVC v143 toolset as well. (Not build with module support cuz it's broken...)
Reviewers:
=> Make `ut` compiled by MSVC v143 toolset.

include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- #505
Solution:
- Return true only if `value`/`epsilon` is ___public static member object___, otherwise (___not defined___/___private___/___non-static member object___/___static method___/___non-static method___) return false.
- Add tests to verify the fix.
Issue: #505 
Reviewers:
@krzysztof-jusiak @80Ltrumpet
=> Fix `has_value_v` and `has_epsilon_v` not being restrictive enough.

CMakeLists.txt
Problem:
- Install path `include/ut-1.1.9/include/boost` is a bit messy for CMake to import `boost/ut.hpp` with CMake command `find_path`.
```cmake
find_path(ut_INCLUDE_DIR "ut-1.1.9/include/boost/ut.hpp" REQUIRED)
target_include_directories(main
PRIVATE
"${ut_INCLUDE_DIR}/ut-1.1.9/include"
)
```
Users can use `Boost::ut` if they are familiar with the CMake. 
But it would be better if a more simplified use-case is also available.
Solution:
- When `INCLUDE_INSTALL_DIR` is provided, CMakeLists.txt will use the value.
```console
$ cmake -S . -B build -DINCLUDE_INSTALL_DIR="include"
...
$ cmake --build build --target install 
...
```
```cmake
find_path(ut_INCLUDE_DIR "boost/ut.hpp" REQUIRED)
target_include_directories(main
PRIVATE
${ut_INCLUDE_DIR}
)
```
=> cmake: allow user defined INCLUDE_INSTALL_DIR

include/boost/ut.hpp, test/ut/ut.cpp
Under certain conditions, the reporter's summary handler can be called
by the runner more than once. The default reporter handled such cases
correctly, but the runner can be configured with a user-provided
reporter type that may not align with that assumption. Moving the
responsibility to only call the reporter's summary handler once to the
runner aligns with user expectations and prevents bugs.
Problem:
- The summary handler for `ut::reporter`-like types may be called by `ut::runner` multiple times.
Solution:
- Move the responsibility for checking if the reporter's summary handler has already been called from `ut::reporter` to `ut::runner`.
Issue: #515
Reviewers:
=> Call reporter summary handler once from runner

test/ut/ut.cpp
Problem:
```
/home/runner/work/ut/ut/test/ut/ut.cpp: In constructor ‘test_has_member_object::private_member_object_value::private_member_object_value(int)’:
/home/runner/work/ut/ut/test/ut/ut.cpp:31:42: error: declaration of ‘value’ shadows a member of ‘test_has_member_object::private_member_object_value’ [-Werror=shadow]
/home/runner/work/ut/ut/test/ut/ut.cpp: In constructor ‘test_has_member_object::private_member_object_epsilon::private_member_object_epsilon(int)’:
/home/runner/work/ut/ut/test/ut/ut.cpp:54:46: error: declaration of ‘epsilon’ shadows a member of ‘test_has_member_object::private_member_object_epsilon’ [-Werror=shadow]
```
Solution:
- Rename `value`/`epsilon` to `value_`/`epsilon_`, respectively.
Issue: #
Reviewers:
=> Fix gcc shadow errors.

include/boost/ut.hpp
Problem:
- Since `__cpp_lib_source_location` is defined in `<source_location>` and `<version>`, it is defined only if  `<source_location>` or `<version>` is included before `<boost/ut.hpp>`.
- If `<source_location>` is included in one test file and not in another test file it triggers a segmentation fault.
Solution:
- Use `#if __has_include(<source_location>)` instead of `#if defined(__cpp_lib_source_location)`.
=> Include <source_location> if it is found

CMakeLists.txt
Fix #531
CPM use causes failed builds if a build server has restricted / no internet access.
Problem:
- When used in-source header-only on build servers with limited network access, there is no need for the install step. The use of CPM causes a mandatory network access that fails, breaking the build.
Solution:
- Make it possible to disable the CPM / install steps.
Issue: #531 
Reviewers:
@kris-jusiak
=> #531 - Make it possible to disable use of CPM

include/boost/ut.hpp
D:\dev\vcpkg\installed\x64-windows\include\boost\ut.hpp(881) : error C2220: the following warning is treated as an error D:\dev\vcpkg\installed\x64-windows\include\boost\ut.hpp(881) : warning C4702: unreachable code D:\dev\vcpkg\installed\x64-windows\include\boost\ut.hpp(881) : warning C4702: unreachable code https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4702?view=msvc-170 MSVC treats code after return statements as unreachable. By moving the second return inside the try block then there will no longer be two return statements on catch.
Problem:
- if you warnings and error on warnings on this will trigger an error. MSVC sees code after return statements.
Solution:
- Move the last return statement into the try block.
Issue: #
Reviewers:
@ …
=> warning C4702: unreachable code with try catch blocks.

cmake/AddCustomCommandOrTest.cmake, example/cfg/parallel_runner.cpp, include/boost/ut.hpp, test/ft/test_suite_1.cpp, test/ft/test_suite_2.cpp, test/ft/test_suite_3.cpp
Hey, this is a follow-up and proof-of-concept for a basic command-line feature as outlined in 
* #550
What has been done:
-
* added Catch 2-style command-line parsing that can be invoked via `boost::ut::detail::cfg::parse(argc, argv);`
for most compilers/OSes this is done automatically and the definition in `int main(...)` is optional. 
Windows/MSVC may need to define this explicitly in 'main(..)`. But not a breaking change and fully backward compatible.
* added (legacy-style) junit-type xml reporting
N.B. to note: the reporter implementation needs/implemented a nested map structure since some of the information/reporting for xml needs to out-of-order w.r.t. the order in which the tests have been executed. This makes it easier w.r.t. having arbitrary post-processed outputs but -- to be …
=> IDE integration: cmd-line & junit-type reporter

include/boost/ut.hpp
Added check for negative and cast to std::size_t.
Problem:
- std::stoll returns long long. It's being assigned to a std::size_t.
/mnt/d/dev/OpenVIII_CPP_WIP/cmake-build-debug-wsl-clang15/_deps/ut_fetch-src/include/boost/ut.hpp:745:27: error: implicit conversion changes signedness: 'long long' to 'std::size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
std::size_t val = std::stoll(argument, &last);
~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Solution:
- Added check for negative and cast to std::size_t.
Issue: #
Reviewers:
@
=> std::stoll returns long long. It's being assigned to a std::size_t.

.github/workflows/emscripten.yml, CMakeLists.txt, include/boost/ut.hpp, test/ut/CMakeLists.txt, test/ut/ut.cpp
Problem:
I tried using ut in a project which has emscripten as one of it's build targets and hit some issues.
Solution:
Ideally UT would add emscripten as one of it's supported targets with the correct cmake and a CI that ensures that compatibility is not broken over time. 
I realize that asking for supporting a complete new target is a big ask, that's why I start this as a draft PR to:
- show the necessary changes as far as I was able to solve the problems and the remaining problems
- see if others have already experimented in this direction and seek solutions on the outstanding problems
- ask whether the ut maintainers would be interested in adding emscripten and get early feedback
The current state is that the project builds, but the tests do not run through. Things that have been …
=> Emscripten: add CI and fix/disable unsupported features

include/boost/ut.hpp
This simply adds same basic args injection for Windows system.
Problem:
- CLI introduced in #553 did not support MSVC
Solution:
There is no `__attribute__((constructor))` equivalent for MSVC and the closest mechanism I have found ([init_seg](https://learn.microsoft.com/en-us/cpp/preprocessor/init-seg)) did not help. Global/static variables initialization order seems to be not so obvious problem.
For now, `__argc`/`__argv` are simply used to initialize global `cfg::largc`/`cfg::largv`.
Follow up for issue #550
---
PS. I am about to open PR with proposal for explicit `argc`/`argv` passing through manual `ut::cfg<>.run` call.
=> Add basic CLI implicit argc/argv capturing for MSVC

README.md, example/fatal.cpp, include/boost/ut.hpp, test/ut/ut.cpp
The current usage of making tests fatal does not allow custom messages. This allows to stream out a `fatal` to the output to make an expected fatal. This is an alternative to streaming into a fatal.
A few drive-by fixes to make the tests work with Clang 17.
=> Allows custom messages for fatal tests.

README.md, example/log.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Sometimes it's needed to write a custom message that can only be written when the test fails. It's not possible to directly steam these messages, instead lazy evaluation is needed. A typical example is to stream a std::expected's error when it has no value. This is implemented by using a callable that is only called when ut's expect fails.
=> Implements streaming for invocable types.

README.md, example/log.cpp, include/boost/ut.hpp, test/ut/ut.cpp
This makes it possible to use the C++20 formatting library next to the existing stream operator when creating log messages. This feature is only available when the standard library used has format support.
=> Adds format support for logging.

include/boost/ut.hpp
Problem:
- `std::format_string` was retroactively exposed in C++20 by [P2508R1](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2508r1.html)
Some STL implementations may not have it implemented (e.g. one shipped with MSVC cl.exe 19.34.31935).
Solution:
- Check feature test flag `__cpp_lib_format >= 202207L`, use `std::string_view` when too old.
- Alternatively, we could require `__cpp_lib_format >= 202207L` to enable `BOOST_UT_HAS_FORMAT`
=> Fix compilation if std::format_string is not known

include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- std::regex include takes multiple seconds to compile.
Solution:
- Implement utility::regex_match instead.
=> :fire: Speed up compilation times by not using std::regex

include/boost/ut.hpp
Problem:
- Incorrect JUnit XML
- In addition to this: the --out flag does nothing, as results always go to std::out and std::err.
Solution:
- Add <testsuite> layer
- "# tests" reported now maps to the amount of assertions
- Fix closing tag of <testsuites/>
- Use output_filename to stream the report to.
Note:
- The adding of <success> and <failure> tags as suggested in #567 was not done.
Testing:
- I tested this by passing a generated Junit file via the --out flag to https://github.com/marketplace/actions/junit-report-action (Github Actions Junit reporter). That reporter seems to be happy with the result now and happily generates reports (allthough not all corner cases were tested).
Issue: #567
Note: I am not well-versed in the modern C++ techniques used in boost-ext::ut. If the approach …
=> Fix JUnit XML generation.

example/parameterized.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
- can't use `std::ranges::iota_view` or other views.
Solution:
- don't require the `value_type` static member typedef
Issue: #
Reviewers:
@
=> allow use of ranges with parameterized tests

cmake/AddCustomCommandOrTest.cmake, example/log.cpp, example/sl.cpp, include/boost/ut.hpp, test/ut/ut.cpp, test/ut/win_compat_test.cpp
Problem:
- `warning STL4038: The contents of <expected> are available only with C++23 or later.`
- `sl.cpp(15,19): error C3688: invalid literal suffix '_i'; literal operator or literal operator template 'operator ""_i' not found`
- `ut.cpp(93,5): error C7595: 'std::source_location::current': call to immediate function is not a constant expression`
- See reported bug [here](https://developercommunity.visualstudio.com/t/Error-calling-consteval-function-from-an/1669482).
- `std::max` clashes with `Windows.h` `max()` macro.
Solution:
- Use `#ifdef __cpp_lib_expected` instead of `__has_include(<expected>)`, the latter isn't reliable.
- Make sure `ut.hpp` is compatible with `Windows.h` (push & pop `min` & `max`).
- Work around bugs in MSVC.
**Note** that we also need #592 for the build to pass …
=> Fix MSVC warnings and compile errors

test/ut/win_compat_test.cpp
Problem:
- Preprocessor error out since `mingw-gcc` doesn't define `min` or `max` in its `Windows.h` header.
Solution:
- Don't check for `min` or `max` defines when building with mingw.
Reviewers:
@kris-jusiak
=> Fix `win_compat_test.cpp` when building with mingw

example/expect.cpp, include/boost/ut.hpp
Problem:
- https://github.com/boost-ext/ut/discussions/615
Solution:
- is_stream_insertable_v and reserved identifier fix
Checked locally with gcc and clang, added few tests 
Strange feeling to write c++17 code after many month of only c++20 and up .. hard to examine if the type trait have sense .. i hate old enable_if_t , long live concepts ;-)
=> is_stream_insertable_v and reserved identifier fix

README.md
Problem:
There was a typo in the README
Solution:
Add missing "
=> README.md: Add missing " to example.

include/boost/ut.hpp
Resolved an issue where command line arguments were ignored, specifically when the program was compiled with Clang. The problem was addressed by correctly assigning the priority in __attribute__((constructor(101))), ensuring proper initialization and consistent behavior across compilation environments."
Problem:
Command line arguments were ignored, specifically when the program was compiled with Clang.
Solution:
Assigning the priority in `__attribute__((constructor(101))) inline void cmd_line_args(int argc, const char* argv[])`
Issue: #590
Reviewers:
=> Fix: Ensure Command Line Arguments Are Respected in Clang Compilation

include/boost/ut.hpp
Problem:
- With MinGW on windows and maybe on other platforms the cmd_line_args function sets cfg::largc to -1 and trigger a segmentation fault in parse.
Solution:
- if `argc < 0` then use 0 instead in parse.
Issue: #
Reviewers:
@
=> Fix a segmentation fault caused by a negative argc

README.md
Problem:
- Compilation error of readme example
Solution:
- Resolved compilation error
Issue: #627 
Reviewers:
@kris-jusiak
=> Readme, fix fatal expr custom message example

include/boost/ut.hpp
Problem:
Without a newline, the suit name and "tests" label are not separated.
===============================================================================
Suite globaltests:   0 | 1 failed
asserts: 0 | 0 passed | 1 failed
Solution:
Add newline
===============================================================================
Suite global
tests:   0 | 1 failed
asserts: 0 | 0 passed | 1 failed
Issue: #
Reviewers:
@
=> Add missing newline to print_console_summary

CMakeLists.txt
Problem:
- Cannot disable UT install targets when UT is included as a subproject.
Solution:
- Add a `BOOST_UT_ENABLE_INSTALL` option for enabling installation targets. By default, this variable is enabled if the project is a top-level project (not a subproject).
Issue: #633
Reviewers:
@
=> Add Option for Enabling Install Targets

.github/workflows/emscripten.yml, .github/workflows/install.yml, .github/workflows/install_download_all.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .github/workflows/windows_shared.yml, .gitignore, CMakeLists.txt, example/parameterized.cpp, include/boost/ut.hpp, test/CMakeLists.txt, test/test.sh, test/test_download_all.sh
Problem:
Install, enscriptem and macos pipelines were failing. 
Install because there was `find_package(ut )` with specific old version if BOOST_UT_TEST_INSTALLED_VERSION at `test/CMakeLists.txt`. 
enscriptem because there was ask specific ask for `set(CMAKE_CXX_STANDARD 20)` at `test/CMakeLists.txt` and there was an example that could not be compiled. I've fixed cmake and wrapped with macro the failing part of the example
macos was failing because it couldn't install pyyaml. After my friend at live through discord tried to reproduce and made mistake, it was found out that `pipx install pyaml` works, but `pipx install pyyaml` doesn't work. IDK why. Though, there's test fail at macos pipeline, and a guy said it's because source_location is broken on macos.
Also there was some bad docstring …
=> little fix cmake + little fix github pipelines

README.md, include/boost/ut.hpp
Problem:
- While building my project with codespell, I found some typos in the files README.md and ut.hpp
Solution:
- Typo fixes found by the codespell utility have been provided
Issue: #
Reviewers:
=> Typo fixes in README.md and ut.hpp

CMakeLists.txt, cmake/AddCustomCommandOrTest.cmake
Problem:
CMake 3.31 now rejects `add_custom_command` with invalid arguments ([CMP0175](https://cmake.org/cmake/help/latest/policy/CMP0175.html))
Solution:
Specify `POST_BUILD` in all add_custom_command calls.
Issue: <None>
Reviewers:
@kris-jusiak
=> fix(cmake): CMP0175

.clang-tidy, include/boost/ut.hpp
Problem:
- the `AnalyzeTemporaryDtors` options has been removed from [clang-tidy-18](https://github.com/llvm/llvm-project/issues/62020) 
- `parse()` triggers `clang-analyzer-core.NullDereference` from clang-tidy-19
Solution:
- remove 'AnalyzeTemporaryDtors' from .clang-tidy,
- add `argv != nullptr` checking in `parse()`.
Issue: #
Reviewers:
@
=> fix clang-tidy-19 problems

cmake/AddCustomCommandOrTest.cmake, include/boost/ut.hpp, test/ut/ut.cpp
**Problem:**
Currently, when the test output is printed, it only uses the test name, but not the test type. For the BDD test example from the README (modified to make it fail: https://godbolt.org/z/1T6bnzcez):
```c++
int main() {
using namespace boost::ut;
using namespace boost::ut::bdd;
"vector"_test = [] {
given("I have a vector") = [] {
std::vector<int> v(5);
expect((5_ul == std::size(v)) >> fatal);
when("I resize bigger") = [=] {
mut(v).resize(10);
then("The size should increase") = [=] {
expect(9_ul == std::size(v));
};
};
};
};
}
```
the output looks like this:
```
Running test "vector"... 
Running test "I have a vector"... 
Running test "I resize bigger"... 
Running test "The size should increase"... FAILED
in: /app/example.cpp:17 - test condition:  [9 == 10]
```
Not that though we …
=> Improve BDD test output

test/ut/ut.cpp
Problem:
In #581 it was reported that the number of assertions differ in parameterized tests using a `for` loop vs `operator|`.
Solution:
The underlying issue was fixed by #640 but this PR adds a test to ensure that the issue does not occur again.
Issue: #581
=> Add test for issue number 581

example/matcher.cpp, include/boost/ut.hpp, test/ut/ut.cpp
Problem:
Since C++17 was used initially, ut uses a custom implementation of concepts. 
Solution:
Since ut now uses C++20, we can use the actual concepts.
=> Use concepts instead of SFINAE

include/boost/ut.hpp
Problem:
The problem I tried to fix in #657 is still not fixed for parameterized tests.
Solution:
Do not unconditionally set the parameterized tests' type to `"test"` but pass the actual test type.
=> Improve parameterized BDD tests

include/boost/ut.hpp
Problem:
-
detected via the 'warning-as-error' flag:
On many architectures `unsigned long long' is identical to 'std::size_t` but not, for example, on all x86_32, WASM, some MSVC versions.
Solution:
-
explicit `static_cast<std::size_t>(..)`.
=> Fix ull->size_t conversion warning

CMakeLists.txt, include/boost/ut.cppm, include/boost/ut.hpp
Problem:
It is hard to use cxx modules in a single header file.
Solution:
It should be separated into a .cppm file.
Issue: #669
Reviewers:
@kris-jusiak
Note that I'm not expert on boost/ut, I just happened to use its module system yesterday, I liked it a lot but needed to adapt it... I think this change is good.
Anyway, I broke the BOOST_UT_DISABLE_MODULE, because it was easier to create a logic where modules are disabled by default (which is 99% the case), and then, the .cppm file creates a definition BOOST_UT_CXX_MODULES 1, allowing the .hpp to set BOOST_UT_EXPORT export, and also rejecting all sorts of #include in the hpp.
Maybe it's best to remove it from CMakeLists.txt and just assume modules are disabled, unless someone decides to use the .cppm, which will automatically enable …
=> separate .cppm file for cxx modules (closes #669)

include/boost/ut.hpp
The `reporter` correctly adds a newline after `SKIPPED`, but `reporter_junit` doesn't. 
Problem:
- When skipping a test, the console reporter does not add a newline after printing `SKIPPED`.
Solution:
- Adding a newline after printing `SKIPPED`.
Issue: #653 
Reviewers:
@kris-jusiak
=> Add newline after reporting a SKIPPED test

README.md
Problem:
Not a real problem, but header/module on README used to imply a single file, but now the files are different... maybe it's best for newcomers to understand that two files are needed for modules, but a single one is needed for header-only, as usual.
Solution:
Small change in README, pointing to both files independently.
Issue: Didn't open any.
Reviewers:
@kris-jusiak
=> Small improvement in README, to directly indicate the module cppm

.bazelrc, .gitignore, BUILD.bazel, MODULE.bazel, example/BUILD.bazel
Problem:
Currently there's no support for bazel build
Solution:
support bazel build
Necessary files are: MODULE.bazel and BUILD.bazel
Support file are: example/BUILD.bazel
To run this, just install bazel (recommended through NVM/NPM bazelisk package):  `$ bazel build ...`
Issue: #680
Reviewers:
@kris-jusiak
=> support bazel build, closes #680
