boost-ext/ut

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :lipstick: :new: [reporter] Add colors to the output

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [reporter] Use check mark instead of OK

---

README.md
example/module.cpp
include/boost/ut.mpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: :wrench: [ut] Introduce `ut` module using `ut.mpp`

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Update quick start with module

---

README.md
include/boost/ut.hpp
include/boost/ut.mpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] v1.0.1

---

README.md
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [source_location] Use  and  if  is not available

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Update examples output

---

README.md
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: Use ❌ for FAILED for consistency with ✔️

---

example/module.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [example] Simplify `module` example

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :art: [core] Limit `std` dependencies (part 1/N)

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :art: [core] Limit `std` dependencies (part 2/N)

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :art: [core] Limit  dependencies (part 3/N)

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :art: [core] Limit `std` dependencies (part 4/N)

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :art: [core] Limit  dependencies (part 5/N)

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :art: [core] Limit  dependencies (part 6/N)

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Improved benchmark table

---

README.md
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:wrench: [ut] BOOST_UT_INTERFACE using statements

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :books: [README] Benchmark results from gtest

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Update benchmarks

---

include/boost/ut.hpp
test/ft/CMakeLists.txt

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: [ut] No exceptions support

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :books: [README] Benchmarks update

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: :books: [README] Benchmarks anchor

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:arrow_up: :racehorse: :books: [README] Update benchmark results

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: :arrow_up: [ut] Bump UT version to `1.1.0`

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: :wrench: [README] Fix try_it_online link

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:bug: [ut] Compilation fix for clang-trunk

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Headers vs PCH vs C++ Modules benchmark

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: :racehorse: [README] Add binary size images

---

example/log.cpp
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :lipstic: [log] Only print new line with the first message

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Fixup broken godbolt links

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:arrow_up: :books: [README] Update module wandbox link

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Update logo size

---

include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:bug: [test] Fix SFINAE condition for empty lambdas overload

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Fix module example

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :lipstick: :racehorse: [ut] Refactor operators to cache the result

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Bind  to gcc-9.2

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Bind examples to gcc-9.2

---

README.md
example/expect.cpp
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: [expect] Alternative  syntax

---

README.md
example/expect.cpp
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: [expect] Expose alternative `eq/neq/gt/ge/lt/le` for comparisons

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] How it works?

---

README.md
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:arrow_up: [ut] Bump version to `1.1.1`

---

README.md
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :lipstick: [ut] Apply `[[nodiscard]]` attribute

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] API spec

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Fix formatting

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Fix typo in `hello world` example

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Fix typos

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README} operator bool impl

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] details

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] API additions

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Ovierview/Features

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Fix indents

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Cleanup

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: :books: [README] Tutorial

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :books: [README] Improve the layout

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] API runner/reporter

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] API cleanup

---

README.md
example/matcher.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

Example matcher

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Layout refactor

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Open overview

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Tutorial update

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Tutorial/Overview

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Examples cleanup

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Cleanup assertions example

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: [benchmarks] Add boost.test

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Examples indent

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Tests details paragraph

---

README.md
example/BDD.cpp
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [BDD] Use Given/When/Then instead of given/when/then

---

README.md
example/BDD.cpp
include/boost/ut.hpp
test/ut/ut.cpp

This reverts commit 0cdc73a8749d78201d59b542e060d7edcc65343d.
Problem:
-
Solution:
-
Issue: #
Reviewers:
@

Revert ":art: [BDD] Use Given/When/Then instead of given/when/then"

---

README.md
example/skip.cpp
example/test.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :books: [README] Cleanup test examples

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [FAQ] C++20 features

---

README.md
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:arrow_up: [version] Bump version to v1.1.2

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Typos/tweaks

---

README.md
example/cfg/printer.cpp
example/cli.cpp
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [colors] Allow to change colors by overriding the config

---

example/cli.cpp
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [colors] Use pass/fail instead of green/red

---

example/cfg/printer.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:bug: `printer` should `std::forward<T>`

---

README.md
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:arrow_up: Bump version to v1.1.3

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Typo fix

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Motivation

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Benchmarks ut name

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Section for ut png

---

example/CMakeLists.txt
example/tmp.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: [Example] TMP tests

---

README.md
example/section.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :books: [README/Example] Use `should` for sections

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Printer example

---

README.md
example/section.cpp
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: [ut] Sections with mut

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Update colors API cfg

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Motivation section

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Document mut API

---

README.md
example/suite.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Suite example

---

example/should.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [example] Simplify should example

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Quick start doc

---

README.md
example/mut.cpp
example/should.cpp
example/suite.cpp
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:arrow_up: Bump version to v1.1.4

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:racehorse: [benchmark] Add incremental build

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:bug: [README] Fix broken png links

---

example/minimal.cpp
example/mut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [example] Simplify and add additional comments

---

example/using.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [example] using refactor

---

include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:new: :art: [source_location] Source location for test

---

include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:white_check_mark: [ut] Fix broken tests

---

README.md
example/BDD.cpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:white_check_mark: [test] Source location with `""_test`

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] C++20 - Designated initializers

---

README.md
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:arrow_up: Version 1.1.5

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Expanded details

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Reference menu

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Menu

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Ability to collapse the main section

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] Tweak Quick Start image size

---

example/should.cpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [example/ut] New lines

---

CMakeLists.txt

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:wrench: Add CMake Interface Library, Fix #258

---

example/using.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: [example] Using example with more operators

---

README.md
example/parameterized.cpp
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

For parameterized

---

example/tmp.cpp
include/boost/ut.hpp
test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :new: [type] Support for getting type from a value - type<>(t)

---

README.md
example/parameterized.cpp
include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:art: :new: :books: [example] Parameterized tests with language syntax

---

README.md

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:books: [README] More motivation

---

README.md

Problem:
- There is no explanation about why using macros might not be the best idea.
- There are few typos/mistakes in the README.
- API spec is not up-to-date.
Solution:
- Extend FAQ answer about macros with more descriptive explanation.
- Fix them.
- Update API with the newest changes in 1.1.5.

:books: [README] Small tweaks to FAQ be more descriptive about macros

---

example/matcher.cpp

Problem:
- Matcher example doesn't show how to make a custom UT operator.
Solution:
- Add `any_of` matcher which demonstrates how to use `ut::op` in order to create a custom matcher.

:art: [example] `any_of` matcher example

---

README.md
include/boost/ut.hpp

Problem:
- The current version is not reflecting stable/new features.
Solution:
- Update version to `1.1.7`.

:arrow_up: [ut] Bump version to `1.1.7`

---

README.md

Problem:
- There are a lot of questions regarding fast compilation times with UT library.
Solution:
- Add a `FAQ` paragraph which explains it in more details.

:books: [README] FAQ - Fast compilation times?

---

README.md
example/gherkin.cpp
include/boost/ut.hpp

Problem:
- Gherkin is only supported in the example.
Solution:
- Move Gherkin support to the core.

:new: [gherkin] Move `gherkin` support to core

---

README.md

Problem:
- There is no gherkin example in README.
Solution:
- Add a simple gherkin feature test to README.

:books: [README] Gherkin example

---

.travis.yml
README.md
include/boost/ut.hpp

Problem:
- The newest versions of compilers aren't tested in travis.
Solution:
- Add `GCC-10/Clang-10/XCode-11.6` to travis matrix.

:arrow_up: :wrench: [travis] Add GCC-10/Clang-10/XCode-11.6

---

README.md

Problem:
- `Quick-Start` link is broken.
Solution:
- Change to `ut-quick-start` instead.

:books: [README] Fix broken link to `Quick-Start`

---

README.md

Problem:
- `User-Guide` is not up-to-date with recent UT changes.
Solution:
- Update README `User-Guide` to reflect recent changes.

:books: [README] Update `User-Guide`

---

README.md

Problem:
- There is no description how to integrate with `conan/cmake`.
Solution:
- Add links to required files in `Tutorial` section.

:books: [README] Tutorial `conan/cmake` integration

---

include/boost/ut.hpp

Problem:
- When `fatal` expression is triggered the source location is not shown
correctly.
Solution:
- Use `value_location<fatal>` with `operator>>` to get the source
location.

:bug: [fatal] Source Location is not present

---

README.md

Problem:
- There is no section about related materials/talks.
Solution:
- Add a section to README's FAQ.

:books: [README] Related meterials/talks

---

.github/CONTRIBUTING.md
README.md

Problem:
- There is no info about contributing in the README.
Solution:
- Add section about contributing which links to .gihtub/CONTRIBUTING.md

:books: :arrow_up: [README] Contributing

---

test/ut/ut.cpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

testing msvc

---

include/boost/ut.hpp

Problem:
-
Solution:
-
Issue: #
Reviewers:
@

:bug: [pretty_name] Wknd for Apple's version of Clang

---

include/boost/ut.hpp
test/ut/ut.cpp

Add sized UDLs:
```
_i8 for std::int8_t
_i16 for std::int16_t
_i32 for std::int32_t
_i64 for std::int64_t
_u8 for std::uint8_t
_u16 for std::uint16_t
_u32 for std::uint32_t
_u64 for std::uint64_t
```

Add sized UDLs, including _i8, _i16, _i32, _i64, _u8, _u16, _u32, u64

---

README.md

Hi there!
The Codacy badge is broken, so I removed it.
Also added the AUR package which I am maintaining.

Remove (broken) Codacy badge, Add AUR Badge

---

include/boost/ut.hpp

Fixes some of the build issues using this project with Clang 17-dev + experimental libc++ std module. It also fixes an build issue with upstream master.

Module build fixes

---

README.md

Problem:
- No example for named suite
Solution:
-
Issue: #
Reviewers:
@

Add named suite example

---

.pre-commit-config.yaml

The file has been removed.
Fixes: c0a7ae4b3dcb9b9a1320cf25ef5465de9ad9cc82

pre-commit: remove unused CMake exclusion
